

language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t jessdev/docker-react -f Dockerfile.dev .

script: 
 - docker run -e CI=true  jessdev/docker-react yarn run test

 
